from fastapi import FastAPI, HTTPException, Depends
from models import PathGenerationRequest, PathGenerationResponse, IntentRequest, IntentResponse
from services.intent_engine import IntentClassificationEngine
from services.embedding_engine import SemanticCache
from services.graph_worker import DeterministicGraphWorker
from services.gemini_service import GeminiOrchestrator
from dotenv import load_dotenv
import logging
import json

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

load_dotenv()

app = FastAPI(
    title="DhiMārga AI Orchestration Tier",
    description="Tier 3 ML Service for intent classification, semantic caching, and Gemini API orchestration",
    version="1.0.0"
)

# Initialize singletons
intent_engine = IntentClassificationEngine()
semantic_cache = SemanticCache(threshold=0.90)
graph_worker = DeterministicGraphWorker()
gemini_service = GeminiOrchestrator()



@app.get("/health")
def health_check():
    return {"status": "Tier 3 AI Orchestration is running"}

@app.post("/api/v1/intent", response_model=IntentResponse)
def classify_intent(request: IntentRequest):
    """ Fast ML inference using DistilBERT to classify user query intent """
    result = intent_engine.classify_intent(request.query)
    return IntentResponse(**result)

@app.post("/api/v1/recommend_path", response_model=PathGenerationResponse)
def get_path_recommendation(request: PathGenerationRequest):
    """
    Core AI Orchestration Pipeline for DhiMarga:
    1. Check Semantic Cache via Cosine Similarity
    2. Deterministic Graph Filter (Topological Prerequisite Check)
    3. Gemini Structured Prompt Generation
    4. Update Cache
    """
    
    # Generate a semantic cache key based on dynamic state
    cache_query = f"{request.learner.target_career_goal} | XP: {request.learner.xp} | Intent: {request.query_intent} | Done: {','.join(map(str, request.completed_node_ids))}"
    
    # 1. Semantic Cache Hit Check (Cosine Similarity via SentenceTransformers)
    cached_result = semantic_cache.search_cache(cache_query)
    if cached_result:
        logger.info("Serving recommendation from Semantic Cache (High similarity hit).")
        return PathGenerationResponse(**cached_result, cached_hit=True)

    # 2. Deterministic Graph Processing
    completed_set = set(request.completed_node_ids)
    
    # We must convert DTOs to dicts for the graph worker processing
    available_nodes_dicts = [node.model_dump() for node in request.available_graph_nodes]
    
    available_nodes = graph_worker.filter_available_nodes(available_nodes_dicts, completed_set)
    
    # Deterministic topological sort (Kahn's Algorithm) to present nodes in mathematically correct sequence
    sorted_node_ids = graph_worker.get_topological_sort(available_nodes)
    
    # Map back to ordered dictionaries
    sorted_available_nodes = [n for node_id in sorted_node_ids for n in available_nodes if n['id'] == node_id]

    if not sorted_available_nodes:
        return PathGenerationResponse(milestones=[], overall_strategy="No paths unlocked. Complete prerequisites first.", cached_hit=False)

    # 3. Call Gemini for Orchestrated Result
    learner_dict = request.learner.model_dump()
    gemini_result = gemini_service.generate_learning_path(learner_dict, sorted_available_nodes, request.query_intent)
    
    response_data = {
        "milestones": gemini_result.get("milestones", []),
        "overall_strategy": gemini_result.get("overall_strategy", "Generated by AI"),
    }

    # 4. Add to Semantic Cache to save token costs on identical future requests
    semantic_cache.add_to_cache(cache_query, response_data)

    return PathGenerationResponse(**response_data, cached_hit=False)

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
